collections/blog.item
As per title, removed hyperlink from author's names as there is already one underneath.
=> Removed author page url from blog post

site.region
GA somehow is not happy to be next to the LeadForensics script. Moving them apart seems to be fixing the issue.
=> Moving GA script to the bottom of the page

site.region
We had two title tags, this isn't valid HTML and could cause a number of problems, including SEO. Also moved the LeadForensics link below the title delcaration, but not sure this really matters.
=> Fix Titles / LeadForensics

collections/blog.list
- [Related story](https://github.com/redbadger/website-honestly/issues/318)
[Blog] text too large on pagination buttons
- Open the PR deployment branch on the page where both navigation buttons are visible, then change the window size to see that everything is fine now. 😸
=> adjust pagination buttons text size

styles/_blog.less
- [Related story](https://github.com/redbadger/website-honestly/issues/311)
[Blog] 'OPINION' tag doesn't get highlighted when clicked on
- Open the PR deployment branch and try to navigate to `Opinion` category and see a beautiful button highlight. Yes, unbelievable 🙀 but true.
=> add missing styles for opinion category

collections/blog.list, styles/_blog.less
- [Related story 1](https://github.com/redbadger/website-honestly/issues/208)
- [Related story 2](https://github.com/redbadger/website-honestly/issues/275)
- [Related story 3](https://github.com/redbadger/website-honestly/issues/301)
1. Blog Listing page title design change
2. Blog search results hover state - underline only appear at the bottom when text wrap
3. Blog text style: Add 10px margin above bullet points
- Checkout to this branch and run our squarespace template locally to see the changes.
=> Visual improvements

collections/blog.list, styles/_blog.less
Fixes: https://github.com/redbadger/website-honestly/issues/198
Try navigating the blog with keyboard and see that right now the image is highlighted after the title of an article.
=> Tab navigation issues

collections/blog.list
I've talked about that with @Monikamu. This PR moves the image on mobile to lay under the title.
Before:
After:
=> fix image position on mobile

styles/_blog.less
- [Related story](https://github.com/redbadger/website-honestly/issues/210)
This fixes iphone5 horizontal scroll bug.
- To test it you have to use physical device or ios simulator. Go to the blog listing page and try to scroll horizontally.
=> fix iphone5 horizontal scrolling bug

styles/_blog.less
[Related story](https://github.com/redbadger/website-honestly/issues/348)
When blog title is long, featured image is shifted to the right
- Open red-badger.com/blog
- Scroll down until you see a blog with a title long enough to be broken into second line
- Observe that featured image is shifted to the right compared to other blogs
=> fix blog image shift issue

styles/_header.less
Refer to issue redbadger/website-honestly#197; tabs were occuring into the hidden (small screen) menu, and menu links were being read three times. Fixed by making the small screen menu use `display: None`, with a hidden trigger to open and close it (as in website-honestly).
=> #197: Removes excess links from screenreader

site.region
Squarespace is actually able to inject valid GA script from site settings. This is better since it will also take care of the AMP situation when all extra scripts are skipped.
=> Removing GA script as it is injected by Squarespace config now

site.region
Squarespace is actually injecting its own OG tags, and their content is relevant to the pages. To remove double declarations this PR deletes our own custom OG tags from the template.
=> Removing custom Open Graph tags to let SquareSpace correctly take over

collections/blog.item
Before, when sharing a blog post on twitter, the tweet came up only with the url to the post. Now it will come up with 
`title` `url` via @redbadgerteam
=> Add blog title and via on twitter share

blocks/meta-without-author.block, collections/blog.item, styles/_blog-article.less
Duplicate blog CTAs at bottom of page (categories, tags, social sharing links)
=> duplicate meta-tags for desktop window size

styles/_blog-article.less
This adds some very simple styling for code snippets (it works fine with sq-space's code blocks). 
I'm wasn't sure if we have if have any on-brand mono fonts, so I'm defaulting to whatever's available in the browser. `14px` seemed like a good size because snippets wrap easily.
I guess this should go in some way into the RB style guide but not sure where/how that's done 🤔
=> Add default styling for source-code

styles/_blog-article.less, styles/_footer.less
The social icons in the footer and in each Share This Article section now have a hover over colour.
=> changed hover colour of social icons on the footer and in each blog.

site.region
Footer links now trigger a GA event. Added in for marketing.
The main analytics.js code is injected into squarespace via their code injection interface:
`Settings > Advanced > Code Injection`
=> Adds analytics tracking to footer links

styles/_blog.less
**Description**
The 'delivery' category button was not remaining highlighted when selected.  This button was the only one that had this issue.
**Ticket**
https://trello.com/c/HVstYGvN/108-issue-694-blog-page-the-delivery-button-is-not-staying-highlighted-after-being-selected
=> Highlight 'delivery' category

site.region
This padding adjustment should be within the separate ui pull request #98 rather than here, as it is has a visible effect on screen.
=> Remove padding within header

scripts/greyscale.js
Enable greyscale bar for a11y day. 
Also needs to be done for the main site https://github.com/redbadger/website-honestly/compare/enable-greyscale-bar
=> Enable greyscale bar on blog
