redbadger/blog-squarespace-template

site.region, styles/_blog.less, styles/_header.less
Fixing header fonts and bg color. Also proper margins for blog list.
=> Header font fixes

collections/blog.list, styles/_blog.less, styles/_fonts.less
* Blog title - set color to Badger Black
* Blog title - have hover state with red underline and make it 40px on desktop (M size)
* Author's page - make author headline in Proxima Nova Bold and grey, 24px (s) and 30px of padding
* Go to next page - button text, Proxima Nova bold
=> Design tweaks for homepage

README.md, assets/arrow.svg, collections/blog.item, collections/blog.list, package.json, site.region, styles/_blog-article.less, styles/_blog.less, styles/_footer.less, styles/main.less, template.conf
Implementing responsive blog article view
=> Article view

collections/blog.item, collections/blog.list, styles/_blog-article.less, styles/_blog.less
Displaying list of categories on homepage. Toggling active state of the selected category. This feature implementation assumes that categories will be immutable.
=> Categories on homepage

collections/blog.list, styles/_blog-article.less, styles/_blog.less, styles/_fonts.less
The blog article's body has been changed as following:
* Blog title size
* Paragraph bottom margin
* Main image bottom margin
* Image caption top margin
The articles' list contains the category for every article.
=> Blog content formatting and category in the articles list

styles/_blog-article.less
=> Removing dropcap styles

styles/_blog-article.less
=> Strong style for blog body

README.md
Migrated issues to `website-honestly`
=> Issue Tracking Info

site.region
Attempting to improve tracking on LeadForensics
=> Moving tracking scripts into the head of the page

styles/_blog-article.less
=> Hide featured tag on blog page

site.region
=> Fixed unclosed tag

site.region
Fixes https://github.com/redbadger/website-honestly/issues/295
Fixes https://github.com/redbadger/website-honestly/issues/265
=> Pointed link to Contact Us section on the home page 

site.region
Should fix chrome requesting 3 favicons
=> Change favicon order

site.region
=> Footer links -> Absolute

styles/_blog.less
Fixes [Bug #331](https://github.com/redbadger/website-honestly/issues/331)
=> Fix flickering on titles of search results

site.region
Fixes [this](https://github.com/redbadger/website-honestly/issues/279) on blog
=> fix google maps pointing location

styles/_blog-article.less, styles/_blog.less
Bringing inline link styles up to date with the branding http://brand.red-badger.com/d/WEl30uS4YzKw/red-badger-styleguide-style-guide#/elements/links
=> Link color on hover and a nice transition

scripts/index.js, site.region, styles/_header.less
Fix for https://github.com/redbadger/website-honestly/issues/326
=> Open page (background content) shouldn't be scrollable when mobile nav is open

styles/_blog.less, styles/_colors.less
Fixes issue [#378](https://github.com/redbadger/website-honestly/issues/378), part of PR [#389](https://github.com/redbadger/website-honestly/pull/389)
=> Fix button hover state

styles/_blog-article.less, styles/_blog.less
Issue 396 from Website Honestly https://github.com/redbadger/website-honestly/issues/396
=> Styling buttons to match people page

styles/_blog.less, styles/_colors.less, styles/_fonts.less, styles/_footer.less, styles/_header.less
changed red colours in the footer according to: https://github.com/redbadger/website-honestly/issues/431
=> adjust red colours in the footer

styles/_blog.less
Small change to apply the new badgerOnWhite colour to the blog title underline
=> added new style underline to blog titles

styles/_blog-article.less
As a follow up to the work @dstodolny did for the listings page, and to save his sanity in making more accessibility requests, I've applied the @badgerRedOnWhite colour to a number of elements on the blog article pages.
=> adding new accessible styling to blog article pages

site.region
Merge on Friday at 11:49:42 am
=> remove accessibility bar

circle.yml
Adding CircleCI build and deploy process to this repo. No tests yet, this just solves the problem of sharing credentials to deploy the blog.
=> CircleCI - Build/Deploy Process

bin/register-github-release.js, circle.yml
Using the same mechanism as `website-honestly`.
=> Generate Release Notes

site.region, styles/_footer.less, styles/_header.less
Fixes [#479](https://github.com/redbadger/website-honestly/issues/479)
=> Fixes bug 479 - hover states for small nav bar and footer links

site.region, styles/_header.less
I have amended the navigation for the blog to match the that of website-honestly, ie enlarging the touchable area.  Due to a rebase that I was unable to push, the commit history is disappointing, however without further guidance from someone with a deeper understanding of this, I have left it as is, and at least have learnt something for the future!
=> Mobile side nav touch area tweaks

site.region
=> UX Testing Jobs Link In Header

README.md, package-lock.json, package.json
An easy way to pass options to the local squarespace server.
```npm run dev -- -A```
=> Add npm scripts

site.region
I have added alt text to SVGS within the header and footer.  Additionally, within Squarespace i have added alt text to images within the 20 most popular blog posts, as well as 10 posts that discuss accessibility issues.  In order to try to improve the process so that images are given alt text when the blog post is created, I have written some guidelines for Nathalie, who will amend as necessary and add to the 'How to create a blog post' guidelines.
=> Tenon accessibility improvements

blocks/meta-without-author.block, collections/blog.item, collections/blog.list, site.region, styles/_blog.less
Various fixes including:
- Title and alt tags should be the same
- missing alt tags
- `role="presentation"` in places where alt tags are not needed
- Switch to using the more accessible `@badgerRedOnWhite` as chrome tools picked up a poor colour contrast.
=> Accessibility improvements

site.region, styles/_fonts.less, styles/_header.less
Update navigation design and URIs to be the same as https://github.com/redbadger/website-honestly/pull/628.
=> New navigation

.gitignore, collections/blog.item, styles/_blog-article.less
Currently the h2 and h3 have the same font size.
This adds a h3 specific style
=> add H tag style

site.region
Add Hubspot tracking code to HEAD of template
=> add hubspot tracking to head

package-lock.json, scripts/greyscale.js, site.region, styles/_a11y-day.less, styles/main.less, template.conf
This replicates the changes made to a11y day on the mainsite:
https://github.com/redbadger/website-honestly/pull/750
=> Align a11y day code between main site and blog template

README.md, scripts/amplitude.js, site.region
Required in https://trello.com/c/b07GBdrA/226-implementing-amplitude
Currently uses production amplitude api-key in local development as squarespace does not allow for configuration for this. This could be improved upon at a later date but can be left in for now
For access to Amplitude contact Andrew Cumine, Dominik Piatek, James Muldoon, or Nathalie Goepel
=> Implement Amplitude Tracking

scripts/amplitude.js
Pass amplitude.js through babel/prettier for more native js support and readability
=> Implement Amplitude ES5 JS Support

collections/blog.item, collections/blog.list, scripts/amplitude.js, site.region
- update Amplitude tracking so aligns with website-honestly
- refactor logging
=> Refactor amplitude tracking code
